export const LOADING_APP = 'LOADING_APP';
export const LOADING_SUCCESS = 'LOADING_SUCCESS';
export const LOADING_ERROR = 'LOADING_ERROR';
export const LOADING_TITLE = 'LOADING_TITLE';
export const LOADING_ARTICLE = 'LOADING_ARTICLE';

